#Spring boot configuration
spring:
  #JPA properties
  jpa:
    show-sql: true
    open-in-view: false

#Server configuration
server:
  port: 8080 #set your port
  error:
    include-message: always

# Logger configuration
logging:
  level:
    org.springframework: info
    org.hibernate: info