#Spring boot configuration
spring:
  main:
    allow-bean-definition-overriding: true
  #JPA properties
  jpa:
    show-sql: true
    open-in-view: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5432/camplanner1
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  sql:
    init:
      platform: postgres

#Server configuration
server:
  port: 8080 #set your port
  error:
    include-message: always

# Logger configuration
logging:
  level:
    org.springframework: info
    org.hibernate: info